//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace GrabImageClient
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GrabImageEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GrabImageEntities object using the connection string found in the 'GrabImageEntities' section of the application configuration file.
        /// </summary>
        public GrabImageEntities() : base("name=GrabImageEntities", "GrabImageEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GrabImageEntities object.
        /// </summary>
        public GrabImageEntities(string connectionString) : base(connectionString, "GrabImageEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GrabImageEntities object.
        /// </summary>
        public GrabImageEntities(EntityConnection connection) : base(connection, "GrabImageEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Images> Images
        {
            get
            {
                if ((_Images == null))
                {
                    _Images = base.CreateObjectSet<Images>("Images");
                }
                return _Images;
            }
        }
        private ObjectSet<Images> _Images;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Images EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImages(Images images)
        {
            base.AddObject("Images", images);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GrabImageModel", Name="Images")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Images : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Images object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Images CreateImages(global::System.Int32 id)
        {
            Images images = new Images();
            images.id = id;
            return images;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] picture
        {
            get
            {
                return StructuralObject.GetValidValue(_picture);
            }
            set
            {
                OnpictureChanging(value);
                ReportPropertyChanging("picture");
                _picture = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("picture");
                OnpictureChanged();
            }
        }
        private global::System.Byte[] _picture;
        partial void OnpictureChanging(global::System.Byte[] value);
        partial void OnpictureChanged();

        #endregion

    
    }

    #endregion

    
}
